development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  
production:
  adapter: postgresql
  encoding: UTF8
  database: <%= ENV['PG_DATABASE'] %>
  pool: 10
  host: <%= ENV['PG_HOST'] %>
  port: <%= ENV['PG_PORT'] %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
